import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { ModeToggle } from '@/components/mode-toggle'
import { cn } from '@/lib/utils'
import { createContext, useContext } from 'react'
import dbService, { DatabaseService } from '@/MongoDB'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  dbService.run();
  const db = dbService;
  
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <ThemeProvider>
          <ModeToggle/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
