import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { cn } from "@/lib/utils";
import { HeadBar } from "@/components/head-bar";
import { ClerkProvider } from "@clerk/nextjs";
import { initialProfile } from "@/lib/initial-profile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await initialProfile();

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(inter.className, "justify-center flex bg-zinc-950")}
        >
          <div className="min-w-[700px] w-[50%]">
            <ThemeProvider>
              <div className="pb-10">
                <HeadBar />
                {children}
              </div>
            </ThemeProvider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
